version: 2
updates:
- package-ecosystem: docker
  directory: "/lua/5.1/alpine"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
    - 3.13.5
