dist: focal
language: python
python: 3.9

services:
  - docker

install:
  - pip install -U wheezy.template

script:
  - python generate.py
  - bash update.sh
  -
    echo "$DOCKER_PASSWORD" |
    docker login -u "$DOCKER_USERNAME" --password-stdin
  -
    docker images --format "{{.Repository}}:{{.Tag}}" |
    awk '/akorn/ && !/none/' | tac |
    xargs -I {} docker push {}
