FROM akorn/lua:5.5-alpine

# Placeholder Dockerfile for LuaRocks on Lua 5.5.
# This file will be overwritten by generate.py based on luarocks/Dockerfile.template
# and the lua5.5 entry in generate.json.

CMD ["luarocks", "--version"]

