name: images

on:
  schedule:
    - cron: "10 4 * * 6"  # At 04:10 on Saturday.
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - run: |
          pip install -U wheezy.template
          python generate.py
      - run: sh ./update.sh
      - uses: docker/login-action@v2
        with:
          username: akorn
          password: ${{ secrets.docker_password }}
      - run: |
          docker images --format "{{.Repository}}:{{.Tag}}" | \
            awk '/akorn/ && !/none/' | tac | \
            xargs -I {} docker push {}
