name: images

on:
  schedule:
    - cron: "10 4 * * 6"  # At 04:10 on Saturday.
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - run: |
          pip install -U wheezy.template
          python generate.py
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v2
        with:
          username: akorn
          password: ${{ secrets.docker_password }}
      - run: sh ./update.sh
